openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://localhost:3000/api/v1
    description: Optional server description, e.g. Main (production) server

security:
  - cookieAuth: []
paths:
  /auth:
    $ref: ../auth/check-auth.yml
  /auth/sign-up:
    $ref: ../auth/sign-up.yml

  /user:
    $ref: ../user/get-user.yml

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: access_token
  schemas:
    User:
      $ref: ../components/user.yml
